### ISSUE TITLE
CDN error - externally hosted script(s) unavailable

### ISSUE THREAD

**Issue by Bro748** [tommilligan/RainWorld-Map#1] opened 2023-11-02 21:27 UTC
I'm getting this error while trying to use the map. Doesn't say what script or give me any more info, but would be nice to have it fixed.
![image](https://github.com/tommilligan/RainWorld-Map/assets/103339131/1c26c586-8f4d-4d5a-bdd5-2ebdbc371ce0)

**Comment by tommilligan** [comment] 2023-11-02 23:41
Wow, I haven't thought about this project in a while! I suspect the issue is something like the jQuery version being EOL. Probably can be fixed by updating the relevant version here: https://github.com/tommilligan/RainWorld-Map/blob/gh-pages/map.html#L3

and then updating usage as required.

I'm not interested in maintaining this project so will archive it - feel free to fork if you want to take it on though

**Closed as completed** 2023-11-02 23:42 UTC
